"""
Django settings for correo project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os.path
import os
import environ

env = environ.Env(

    DEDENVIOS_DEBUG=(bool, False)
)

environ.Env.read_env()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DEDENVIOS_SECRET_KEY')  # 'h3&53k0t0od3b2_(*y+)n-_g5=h1hcex!c8jvlyo&56tm+l01c'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEDENVIOS_DEBUG')

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'dedenvios.apps.DedenviosConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'ssp.apps.SspConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'correo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'correo.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / env('DEDENVIOS_DB_NAME'),
    },
    'dbase_ssp': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': env('SSP_DB_NAME'),
        'USER': env('SSP_USR'),
        'PASSWORD': env('SSP_PWD'),
        'HOST': env('SSP_HOST'),
        'PORT': env('SSP_PORT'),
    },
}

DATABASE_ROUTERS = ['ssp.routers.SspRouter', ]

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

LOGIN_REDIRECT_URL = 'index'

REST_FRAMEWORK = {

    'DEFAULT_AUTHENTICATION_CLASSES': (

        'rest_framework_simplejwt.authentication.JWTTokenUserAuthentication',
    )

}
# conf celery

BROKER_URL = "amqp://{broker_usr}:{broker_pass}@{broker_host}:{broker_port}{broker_vhost}".format(
    broker_usr=os.getenv('DeDe_broker_usr'),
    broker_pass=os.getenv('DeDe_broker_pass'),
    broker_host=os.getenv('DeDe_broker_host'),
    broker_port=os.getenv('DeDe_broker_port'),
    broker_vhost=os.getenv('DeDe_broker_vhost'),
)
